# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

# Template Version
version: 2
# Adds a space at the end of the prompt
final_space: true
console_title_template: "{{ .Shell }} in {{ .Folder }}"
blocks:
- type: prompt
  alignment: left
  segments:
  - type: os
    style: plain
    foreground: "#fff"
    background: "#000"
  - type: path
    style: plain
    # style: powerline
    # powerline_symbol: 
    properties:
      style: letter
      # mapped_locations:
      #   C:\temp: 
