# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

# Template Version
version: 2
console_title_template: "{{ .Shell }} in {{ .Folder }}"
final_space: true

palette:
  white: "#fff"
  light-green: "#56B6C2"
  light-blue: "#5FAAE8"
  light-orange: "#DCB977"
  light-red: #D0666F
  
blocks:
- type: prompt
  alignment: left
  segments:
      
  - type: text
    template: "<#C591E8>\u276f</><#69FF94>\u276f</> "
    style: plain
    foreground: "p:white"

  - type: path
    style: plain
    foreground: p:light-blue
    properties:
      style: letter

  - type: git
    style: plain
    foreground: p:light-green
    template: "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}"
    # template: {{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"
    properties:
      fetch_status: true
      fetch_upstream_icon: true
    #   untracked_modes:
    #     /Users/user/Projects/oh-my-posh/: no
